FROM node:18 as build

ARG REACT_APP_PING_INTERVAL
ENV REACT_APP_PING_INTERVAL=$REACT_APP_PING_INTERVAL

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]